### ISSUE TITLE
jsonld lib is slow

### ISSUE THREAD

**Issue by gjgd** [decentralized-identity/lds-ecdsa-secp256k1-2019.js#7] opened 2019-07-18 14:10 UTC
When running `npm t -- src/__tests__/lds-ecdsa-secp256k1-2019.spec.js` on my machine, I see that every `.compact()` or `canonize()` call takes between 1 and 2 seconds to finish, even with tiny payloads.

Worth investigating

**Comment by OR13** [comment] 2019-09-26 14:31
we can embed the contexts that are being resolved, but then we are responsible for keeping them up to date...

**Comment by OR13** [comment] 2019-09-26 14:31
this is caused by http overhead.

**Comment by OR13** [comment] 2020-01-06 20:26
this can be resolved by bundling contexts / caching them.

**Comment by OR13** [comment] 2020-01-26 22:39
We can consider bundling both DIF and w3id.org security contexts... https://github.com/decentralized-identity/context

**Closed as completed** 2020-03-30 22:46 UTC
